---@meta

---
---@class network
---@field canDetectNetworkStatusChanges boolean
network = {}

---  Makes an asynchronous HTTP or HTTPS request to a URL. This function returns a handle that can be passed to [network.cancel()][api.library.network.cancel] in order to cancel the request.  
--- @param url string The HTTP request URL.
--- @param method string The HTTP method; acceptable values are `"GET"` (default), `"POST"`, `"HEAD"`, `"PUT"`, and `"DELETE"`.
--- @param listener Listener The listener function invoked at various phases of the HTTP operation. This is passed a [networkRequest][api.event.networkRequest] event. The listener function can receive events of the following phases:* `"began"` &mdash; The first notification, contains the estimated size, if known.* `"progress"` &mdash; An intermediate progress notification.* `"ended"` &mdash; The final notification, when the request is finished.By default, the listener will only receive `"ended"` events.  If `params.progress` (see&nbsp;below) is `"upload"` or `"download"`, then the listener will also receive `"began"` and `"progress"` events.If the response body is directed to a file by using `params.response` and the response was successfully written to the file, `event.response` will contain a table indicating the `filename` and `baseDirectory` for the output file.  If the request completes, but produces an error response, then any error response body will be provided as a string in `event.response` instead. This behavior prevents the destination file from being written/overwritten with an error response instead of the desired payload.
--- @param params table? A table that specifies HTTP request or response processing options, including custom request headers or body. The following keys are supported:* `headers` &mdash; Table specifying request header values with string keys.* `body` &mdash; String containing the request body, or alternatively, a table containing the `filename` and optionally `baseDirectory` for a file whose contents are to be used as the request body.* `bodyType` &mdash; String indicating whether a string request body is `"text"` or `"binary"`. Default is `"text"` if `params.body` is a string or `"binary"` if it's a table specifying a file.* `progress` &mdash; String value indicating the type of progess notifications desired, if any. May be `"upload"` or `"download"`. The notification phases include the `"began"` and `"progress"` phase events for the desired direction of progress. Default is `nil`, indicating that only the `"ended"` phase event is desired.* `response` &mdash; Table value indicating that the response body should be written to a file and specify the `filename` and optionally the `baseDirectory` for the response file. If this value is not provided, the response body is provided as a string.* `timeout` &mdash; Timeout in seconds. Default is 30 seconds.* `handleRedirects` A boolean indicating whether automatic redirect handling (the default) is desired.  Set this to `false` if you want to receive 302 responses and handle them yourself.  This may be needed for certain kinds of login schemes or custom cookie handling.Note that if a `filename` table is specified in `params.body` or in `params.response`, `baseDirectory` is an optional [Constant][api.type.Constant] that defaults to [system.DocumentsDirectory][api.library.system.DocumentsDirectory]. In the case of `params.response`, `baseDirectory` cannot be set to [system.ResourceDirectory][api.library.system.ResourceDirectory], since that directory is <nobr>read-only.</nobr>
--- @return userdata
function network.request(url, method, listener, params) end

---  Cancel an outstanding network request made with [network.request()][api.library.network.request], [network.upload()][api.library.network.upload], or [network.download()][api.library.network.download].  
--- @param requestId userdata The request handle provided by [network.request()][api.library.network.request], [network.upload()][api.library.network.upload], or [network.download()][api.library.network.download]. This handle is returned by each of these functions and is also provided in the [networkRequest][api.event.networkRequest] event.
function network.cancel(requestId) end

---  Starts monitoring a host for its network reachability status. This API is designed around the idea that you are monitoring individual hosts and not the hardware directly. Potentially, some hosts might continue to be reachable while others are not due to internet conditions, firewall configurations, authentication rules, and whether you need full DNS routing. 
--- @param hostURL string The host you want to monitor. This may be something like `"www.solar2d.com"`. You should not include `http://` or the port number.
--- @param listener Listener The listener that gets [networkStatus][api.event.networkStatus] events for the specified host. Pass `nil` to unregister the listener that's set for the specified host.
function network.setStatusListener(hostURL, listener) end

---  This API is a convenience method that is very similar to the asynchronous [network.request()][api.library.network.request], except that always attempts to upload the request from a local file that you specify. In fact, this method simply calls [network.request()][api.library.network.request], putting the source `filename` and `baseDirectory` parameters into a `params.body` table, adding `contentType` as a `params.headers` request header value, and specifying `"upload"` progress notifications.   This function returns a handle that can be passed to [network.cancel()][api.library.network.cancel] in order to cancel the request.  
--- @param url string The HTTP request URL.
--- @param method string The HTTP method; should typically be either `"PUT"` or `"POST"` for a file upload.
--- @param listener Listener The listener function invoked at various phases of the HTTP operation. It is passed a [networkRequest][api.event.networkRequest] event. This API provides `"upload"` progress when `progress` is `true`, meaning that the listener will receive events for `"began"`, `"progress"`, and `"ended"` phases. If the `progress` parameter is not enabled, the listener will only be invoked with an `"ended"` phase.
--- @param params table? Table that specifies HTTP request processing options, including custom request headers. The following keys are supported:* `headers` &mdash; Table specifying header values with string keys.* `timeout` &mdash; Timeout in seconds. Default is 30 seconds. Only available on Mac/iOS.* `bodyType` &mdash; String indicating whether a string request body is `"text"` or `"binary"`. Default is `"text"`.* `progress` &mdash; Setting to `true` enables the progress events. Default is `nil`, indicating that only the `"ended"` phase event is desired.
--- @param filename string The name of the file to upload.
--- @param baseDirectory Constant? The directory of the file to upload. Defaults to [system.DocumentsDirectory][api.library.system.DocumentsDirectory] if not provided. 
--- @param contentType Constant? The `Content-Type` of the file being uploaded. While this parameter is optional, `Content-Type` __must__ be provided either via this parameter or via a `params.header` value. 
--- @return userdata
---@overload fun (url:string, method:string, listener:Listener, params:table?, filename:string, baseDirectory:Constant?):userdata
---@overload fun (url:string, method:string, listener:Listener, params:table?, filename:string):userdata
---@overload fun (url:string, method:string, listener:Listener, filename:string, baseDirectory:Constant?, contentType:Constant?):userdata
---@overload fun (url:string, method:string, listener:Listener, filename:string, baseDirectory:Constant?):userdata
---@overload fun (url:string, method:string, listener:Listener, filename:string):userdata
function network.upload(url, method, listener, params, filename, baseDirectory, contentType) end

---  This API is a convenience method that is very similar to the asynchronous [network.request()][api.library.network.request], except that it always attempts to download the response to a local file that you specify. In fact, this method simply calls [network.request()][api.library.network.request], putting the destination `filename` and `baseDirectory` parameters into `params.response` and specifying `"download"` progress notifications.   You can also use [display.loadRemoteImage()][api.library.display.loadRemoteImage] to download and display a remote image in a single API call.  This function returns a handle that can be passed to [network.cancel()][api.library.network.cancel] in order to cancel the request. 
--- @param url string The HTTP request URL.  This must conform to the usual rules for [URLs](https://en.wikipedia.org/wiki/URL) (see example below if you want to use non-ASCII characters in the URL).
--- @param method string The HTTP method; acceptable values are `"GET"` (default) or `"POST"`.
--- @param listener Listener The listener function invoked at various phases of the HTTP operation. This is passed a [networkRequest][api.event.networkRequest] event.This API provides `"download"` progress when `progress` is `true`, meaning that the listener will receive events for `"began"`, `"progress"`, and `"ended"` phases. If the `progress` parameter is not enabled, the listener will only be invoked with an `"ended"` phase.
--- @param params table? Table that specifies HTTP request or response processing options, including custom request headers or body. The following keys are supported:* `headers` &mdash; Table specifying request header values with string keys.* `body` &mdash; String containing the request body, if any.* `timeout` &mdash; Timeout in seconds. Default is 30 seconds.* `bodyType` &mdash; String indicating whether a string request body is `"text"` or `"binary"`. Default is `"text"`.* `progress` &mdash; Setting to `true` enables progress events. Default is `nil`, indicating that only the `"ended"` phase event is desired.
--- @param filename string The name of the file to which the response will be saved.
--- @param baseDirectory Constant? The directory where the file will be saved. Defaults to [system.DocumentsDirectory][api.library.system.DocumentsDirectory] if not provided. Cannot be set to [system.ResourceDirectory][api.library.system.ResourceDirectory] since that directory is <nobr>read-only.</nobr>
--- @return userdata
---@overload fun (url:string, method:string, listener:Listener, filename:string, baseDirectory:Constant?):userdata
---@overload fun (url:string, method:string, listener:Listener, filename:string):userdata
function network.download(url, method, listener, params, filename, baseDirectory) end

